support python3 for newer ubuntu releases

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -17,10 +17,17 @@ set -e
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-
 case "$1" in
     configure)
-        pip install b2
+        if which pip; then
+            PIP=$(which pip)
+        elif which pip3; then
+            PIP=$(which pip3)
+        else
+            echo "pip not found in postinst!" >&2
+            exit 1
+        fi
+        $PIP install b2
     ;;
     
     abort-upgrade|abort-remove|abort-deconfigure)
